### ISSUE TITLE
plot.py crashes if generating long plot with no search hits

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/discordgrapher#5]
```
$ python3 plot.py -i test.txt -l -s "TestStringThatReturnsNoHits"
Reading file: 100%|████████████████████████| 940713/940713 [00:02<00:00, 395404.14 messages/s]
Processing - Stage 1: 100%|████████████████| 940713/940713 [00:05<00:00, 167096.93 messages/s]
Filtering keywords: 100%|██████████████████| 940713/940713 [00:01<00:00, 518430.80 messages/s]
Processing - Stage 2: 0 messages [00:00, ? messages/s]
OK, now generating a long graph.
Preparing: 0 messages [00:00, ? messages/s]
Now crunching numbers...
Traceback (most recent call last):
  File "plot.py", line 154, in <module>
    plotLong()
  File "plot.py", line 24, in plotLong
    r = r[r[:,0].argsort()]
IndexError: too many indices for array
```

Current implementation of plotWeek works properly and returns a rather boring graph.

**Comment by the-emerald** [comment]
```
$ python3 plot.py -i test.txt -w -s "TestStringThatReturnsNoHits"
Reading file: 100%|██████████████████████████████| 940713/940713 [00:02<00:00, 403275.43 messages/s]
Processing - Stage 1: 100%|██████████████████████| 940713/940713 [00:05<00:00, 171722.58 messages/s]
Filtering keywords: 100%|████████████████████████| 940713/940713 [00:01<00:00, 528816.14 messages/s]
Processing - Stage 2: 0 messages [00:00, ? messages/s]
Ok, now generating a week graph.
Preparing: 0messages [00:00, ?messages/s]
Traceback (most recent call last):
  File "plot.py", line 173, in <module>
    plotWeekHour()
  File "plot.py", line 95, in plotWeekHour
    r = r[r[:,0].argsort()]
IndexError: too many indices for array
```

As of 34a94dd the same issue can be found on plotWeekHour()
